name: Generate Metadata

on:
  # Auto-run when markdown or script changes
  push:
    paths:
      - 'weeks/**.md'
      - '.github/scripts/generateMetadata.js'
  # Enable manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run metadata generator
        run: node .github/scripts/generateMetadata.js

      - name: Generate rss.xml
        run: node .github/scripts/generateRSS.js

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add metadata.json rss.xml
          git commit -m "Auto-update metadata.json and rss.xml" || echo "No changes to commit"
          git push

